apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sparse-f021d718d80531ed72126ee36fd059f9
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: openebs-local-nvme-sparse
  local:
    path: /mnt/sparse/disk-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kmova-nvme-u18-n1s16
