apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sparse-node-d5gm-0
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: openebs-rawfile
  local:
    path: /mnt/sparse/disk-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-kmova-helm-default-pool-df036892-d5gm
