script:
  - if [ ! -z $TRAVIS_TAG ] && [ "$TRAVIS_REPO_SLUG" == "kmova/bootstrap" ]; then
      echo "just checking if == works";
      REL_BRANCH=$(echo v$(echo "$TRAVIS_TAG" | cut -d'-' -f1 | rev | cut -d'.' -f2- | rev).x) ;
      echo "Tagging kmova/notes with $TRAVIS_TAG on branch $REL_BRANCH" ;
      ./git/git-cli-release.sh "kmova/notes" "$TRAVIS_TAG" "$REL_BRANCH" || travis_terminate 1 ;
    fi
