apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-nfs-subdir
provisioner: openebs.io/nfs-subdir # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
