apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: kiranmova/nfs-subdir-external-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: openebs.io/nfs-subdir
            - name: NFS_SERVER
              value: 10.47.243.251
            - name: NFS_PATH
              value: /export/pvc-7341cb3b-3d45-40be-b2c4-ea83ed38ab4f
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.47.243.251
            path: /export/pvc-7341cb3b-3d45-40be-b2c4-ea83ed38ab4f
