kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-server-backing-store
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
