kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-nfs-claim
spec:
  storageClassName: openebs-nfs-ganesha
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
