apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-local-sts
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: device
      - name: BlockDeviceTag
        value: "fio-job"
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
