apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/export/pvc-9f0de83b-a978-468e-866c-207d88f1a760/sub-dir1"
    server: 10.47.254.71
